# Dependencies
markdown:         KramdownPygments
kramdown:
  extensions: [smart]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Debug Things
tagline:          Debugging, performance testing, DevOps, and ranting.
url:              
paginate:         5
baseurl:          /
author:
  name:           James Davis
  url:            https://twitter.com/debugthings
  email:          james.l.davis@outlook.com

# Custom vars
version:          1.0.0
github:
  repo:           https://www.github.com/jldgit
post:
  twitembed:      BLANK
lessc: 			  /usr/bin/lessc
less_files: ["/_bootstrap/bootstrap.less"]
less_output:      "/public/css/"